project:
  type: website
  output-dir: docs

website:
  title: "Beining Liu"
  navbar:
    background: dark
    foreground: light
    right:
      - href: home.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: useful-resources.qmd
        text: Useful Resources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full

editor: visual