project:
  type: website
  output-dir: docs

website:
  title: "Beining Liu"
  navbar:
    left:
      - href: 1-home.qmd
        text: Home
      - href: 2-research.qmd
        text: Research
      - href: 3-cv.qmd
        text: CV
      - href: 4-contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false