project:
  type: website
  output-dir: docs

website:
  title: "Beining Liu"
  navbar:
    left:
      - href: home.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false